### ISSUE TITLE
Typo in example email generated

### ISSUE THREAD

**Issue by nehcuy** [RichDom2185/glam-mailer#259]
In the `Compose` tab, generated `Load Example` email contains a minor syntax error in the md text:
```md
Oh, and not to mention, :heart*eyes: \_emojis* :smile: :sparkles: :exclamation:
```

I'm assuming this was what was intended:
```md
Oh, and not to mention, :heart_eyes: *emojis* :smile: :sparkles: :exclamation:
```

**Comment by RichDom2185** [comment]
Thank you for noticing this! Will work on it soon :)
